apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: open-webui
  name: open-webui
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: open-webui
    spec:
      containers:
        - env:
            - name: OPENAI_BASE_URL
              value: http://copilot-api:4141
            - name: OPENAI_API_KEY
              value: a
          image: ghcr.io/open-webui/open-webui
          name: open-webui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui-data
      restartPolicy: Always
      volumes:
        - name: open-webui-data
          persistentVolumeClaim:
            claimName: open-webui-data
