apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - dragonfly.yaml
  - production-configmap.yaml
  - mastodon-main-pvc.yaml
  - rbac.yaml
  - db-migration-job.yaml
  - sidekiq-deployment.yaml
  - streaming-deployment.yaml
  - streaming-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - networkpolicy.yaml
  - ingressroute.yaml
secretGenerator:
  - name: production
    namespace: mastodon
    envs:
      - .env
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/mastodon/mastodon
    newName: ghcr.io/mastodon/mastodon
    newTag: v4.3.7
  - name: ghcr.io/mastodon/mastodon-streaming
    newName: ghcr.io/mastodon/mastodon-streaming
    newTag: v4.3.7
